### ISSUE TITLE
APT repository limited only to amd64 arch.

### ISSUE THREAD

**Issue by vholer** [antmelekhin/ansible-role-microsoft-repository#9]
Repository definition is limited only to `amd64` arch.

https://github.com/antmelekhin/ansible-role-microsoft-repository/blob/d444fc0e5e2dab7ee073f475f89b79df9d8d30e5/templates/microsoft.list.j2#L5-L7

while the repository contains also packages for other archs., e.g. repository configuration provided by Microsoft in e.g. https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb lists also ARMs, see:

```
deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/22.04/prod jammy main
```

**Comment by antmelekhin** [comment]
Fixed via above PR.
